foodtrucks/urls.py
from .import views
from django.urls import path

app_name = 'foodtrucks'

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('all/trucks/',views.alltrucks,name='alltrucks'),
    path('add/truck/',views.addtruck,name='addtruck'), 
    path('edit/truck/<int:truck_id>/',views.edit,name='edit'),   
    path('delete/truck/<int:truck_id>',views.deletetruck,name='deletetruck'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foodtrucks.urls',namespace='foodtrucks'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

foodtrucks/models.py
from django.db import models

class FoodType(models.Model):
    foodtype = models.CharField(max_length=50)

    def __str__(self):
        return self.foodtype

class FoodTruck(models.Model):
    foodtype = models.ForeignKey(FoodType,on_delete = models.CASCADE,related_name = 'food_truck')
    location = models.CharField(max_length=100,null=True)
    owner_name = models.CharField(max_length=50,null=True)
    truck_image = models.ImageField(null=True)
    opening_time = models.CharField(max_length=50)
    closing_time = models.CharField(max_length=50)

    def __str__(self):
        return self.owner_name

foodtrucks/views.py
from django.shortcuts import render,redirect
from.models import *
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
import datetime

def homepage(request):
    last5 = FoodTruck.objects.all().order_by('-id')[:5]
    now = datetime.datetime.now().strftime('%H:%M:%S')
    return render(request,'home.html',{"trucks":last5,"current_time":now})

'''Listing for all the trucks'''

def alltrucks(request):
    query = request.GET.get('trucksearch')
    page = request.GET.get('page',1)

    
    if query:
        trucks = FoodTruck.objects.filter(Q(foodtype__foodtype__icontains = query) | Q(location__icontains = query))
    else:
        trucks = FoodTruck.objects.all()

    paginator = Paginator(trucks,5)
    now = datetime.datetime.now().strftime('%H:%M:%S')
    try:
        truck = paginator.page(page)
    except PageNotAnInteger:
        truck = paginator.page(1)
    except EmptyPage:
        truck = paginator.page(paginator.num_pages)
    return render(request,'foodtrucks/alltruck.html',{"trucks":truck,"current_time":now})

''' Adding New truck'''

def addtruck(request):
    foodtype = FoodType.objects.all()
    truck_dict = {}
    if request.method == 'POST':
        print(request.POST.get('image'))
        truck = FoodTruck.objects.create(
            foodtype = FoodType.objects.get(id=request.POST.get('foodtype')),
            location = request.POST.get('location'),
            owner_name = request.POST.get('owner_name'),
            truck_image = request.FILES['image'],
            opening_time = request.POST.get('open_time'),
            closing_time = request.POST.get('close_time')
        )
        truck.save()
        return redirect('foodtrucks:alltrucks')
    return render(request,'foodtrucks/addtruck.html',{"foodtype":foodtype})


'''Edit Truck Details'''

def edit(request,truck_id):
    foodtruck = FoodTruck.objects.get(id=truck_id)
    foodtype = FoodType.objects.all()
    if request.method == 'POST':
        foodtruck.foodtype = FoodType.objects.get(id=request.POST.get('foodtype'))
        foodtruck.location = request.POST.get('location')
        foodtruck.owner_name = request.POST.get('owner_name')
        if request.FILES.get('image'):
            foodtruck.truck_image = request.FILES['image']
        foodtruck.opening_time = request.POST.get('open_time')
        foodtruck.closing_time = request.POST.get('close_time')
        foodtruck.save()
        return redirect('foodtrucks:edit',truck_id=truck_id)
    return render(request,'foodtrucks/truckedit.html',{"foodtruck":foodtruck,
                                                        "foodtype":foodtype})



def deletetruck(request,truck_id):
    foodtruck = FoodTruck.objects.get(id=truck_id)
    foodtruck.delete()
    return redirect('foodtrucks:alltrucks')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://kit.fontawesome.com/a28b225f4c.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Nuage BizTech Assesment(Food Truck Prototype)</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'foodtrucks:homepage' %}">FoodTruck</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'foodtrucks:homepage' %}">Home</a>
                    </li>
                </ul> -->

            </div>
            {% if not request.path == '/all/trucks/' %}
            <div class="nav-item">
                <a class="nav-link white" aria-current="page" href="{% url 'foodtrucks:alltrucks' %}">All Trucks</a>
            </div>
            {% endif %}
            <div class="nav-item">
                <a class="nav-link white" aria-current="page" href="{% url 'foodtrucks:addtruck' %}">Add Trucks</a>
            </div>
            {% if request.path == '/all/trucks/' %} 
            <form class="d-flex search" action="{% url 'foodtrucks:alltrucks' %}">
                <input class="form-control me-2" type="search" name="trucksearch" placeholder="By food type or location" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
             {% endif %}



        </div>
    </nav>

    <div class="container-fluid">
        {% load static %}
        {% block content %} {% endblock %}
    </div>

</body>

</html>

templates/foodtrucks/addtruck.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-6">
            <div class="card add-card" id="add_truck">
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="" id="add_truck_form">
                        <div class="text-center">
                            <h3>Add Truck Form</h3>
                        </div>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="foodtype">Select Food Type</label>
                            <select name="foodtype" id="foodtype" class="form-control">
                                <option value="">Select Position</option>
                                {% for x in foodtype %}
                                <option value="{{x.id}}">{{x.foodtype}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="playername">Owner Name</label>
                            <input type="text" class="form-control" id="owner_name" name="owner_name"
                                aria-describedby="emailHelp" placeholder="Enter Owner Name">
                        </div>
                        <div class="form-group">
                            <label for="playercredit">Location</label>
                            <input type="text" class="form-control" name="location" id="location"
                                placeholder="Enter You Location">
                        </div>
                        <label>Truck Image</label>
                        <div class="form-group">
                            <input type="file" class="form-control" id="truck_image" name='image'>
                        </div>
                        <div class="form-group">
                            <label for="input_starttime">Opening Time</label>
                            <input placeholder="Selected time" type="time" id="input_starttime"
                                class="form-control timepicker" name="open_time">
                        </div>
                        <div class="form-group">
                            <label for="input_starttime">Closing Time</label>
                            <input placeholder="Selected time" type="time" id="input_starttime"
                                class="form-control timepicker" name="close_time">
                        </div>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

    });
</script>
{% endblock %}

templates/foodtrucks/alltruck.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="container">
  <div class="row">
    {% if trucks %}
    {% for x in trucks %}
    <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete {{x.owner_name}}'s truck?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <a href="{% url 'foodtrucks:deletetruck' truck_id=x.id %}" class="btn btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div> -->


    <div class="col-md-4 truck-card">
      <div class="card">
        <img src="/media/{{x.truck_image}}" class="card-img-top" alt="{{x.truck_image}}">
        <div class="card-body">
          <h5 class="card-title">Food Type: {{x.foodtype}}
            <a class="d-right edit-btn" href="{% url 'foodtrucks:edit' truck_id=x.id %}" style="color: #333333;"><i
                class="fas fa-pen"></i></a>
            <a class="d-right delete-btn" href="{% url 'foodtrucks:deletetruck' truck_id=x.id %}" style="color: red;"><i
                class="fas fa-trash"></i></a>
            <!-- <span class="d-right" style="color: red;" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-trash"></i></span> -->

          </h5>
          <p class="card-text location">Location: {{x.location}}</p>
          <div class="card-info">
            <p class="card-text"><i class="fas fa-user"></i> Truck Owner: {{x.owner_name}}</p>
            <p class="card-text"><i class="fas fa-lock-open"></i> Opening Time: <span
                id="opentime">{{x.opening_time}}</span></p>
            <p class="card-text"><i class="fas fa-lock"></i> Closing Time: <span
                id="closetime">{{x.closing_time}}</span></p>
            <p class="card-text"><i class="fas fa-store"></i> Truck Status:
              <span id="truck-status">
                {% if current_time > x.opening_time and current_time < x.closing_time %}
                  OPEN
                {% else %}
                 CLOSED
                {% endif %}
              </span>
            </p>

          </div>
        </div>
      </div>
    </div>



    <br>
    {% endfor %}
    {% else %}
    <div class="row">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <p>OOPS! NO DATA FOUND ACCORDING TO YOUR SEARCH</p>
          <p><a href="{% url 'foodtrucks:alltrucks' %}">Get back to all trucks.</a></p>
        </div>
      </div>
    </div>
    {% endif %}
  </div>

  <div class="paginator">
    {% if trucks.has_other_pages %}
    <ul class="pagination">
      {% if trucks.has_previous %}
      <li class="page-item"><a href="?page={{ trucks.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="disabled page-item"><span>&laquo;</span></li>
      {% endif %}
      {% for i in trucks.paginator.page_range %}
      {% if trucks.number == i %}
      <li class="active page-item"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
      <li class="page-item"><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if trucks.has_next %}
      <li class="page-item"><a href="?page={{ trucks.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="disabled page-item"><span>&raquo;</span></li>
      {% endif %}
    </ul>
    {% endif %}
  </div>


</div>




</div>

<script>

  {% for x in trucks %}

  var opentime = '{{x.opening_time}}';
  var closetime = '{{x.closing_time}}';
  console.log(opentime);
  var time = new Date();
  var currentTime = time.toLocaleString('en-US', { hour: 'numeric', minute: 'numeric', hour12: true })
  console.log(currentTime);
  if (currentTime > opentime && currentTime < closetime) {
    console.log('Open');
    document.getElementById('truck-status').innerHTML = "Open";
    $('#truck-status').html("Open");
  }
  else {
    console.log('close');
  }
  {% endfor %}

</script>



{% endblock %}

templates/foodtrucks/truckedit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-6">
            <div class="card edit-card" id="add_truck">
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="" id="add_truck_form">
                        <div class="text-center">
                            <h3 style="margin-top: 0px;">Edit Truck Form</h3>
                        </div>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="foodtype">Select Food Type</label>
                            <select name="foodtype" id="foodtype" class="form-control">
                                <option value="">Select Position</option>
                                {% for x in foodtype %}
                                <option value="{{x.id}}" {% if x.id==foodtruck.foodtype.id %}selected{% endif %}>
                                    {{x.foodtype}}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="playername">Owner Name</label>
                            <input type="text" value="{{foodtruck.owner_name}}" class="form-control" id="owner_name"
                                name="owner_name" aria-describedby="emailHelp" placeholder="Enter Owner Name">
                        </div>
                        <div class="form-group">
                            <label for="playercredit">Location</label>
                            <input type="text" class="form-control" name="location" id="location"
                                placeholder="Enter You Location" value="{{foodtruck.location}}">
                        </div>
                        <label>Truck Image</label><br>
                        <label>Current Image: {{foodtruck.truck_image}}</label>
                        <div class="form-group">
                            <input type="file" class="form-control" id="truck_image" name='image'
                                value="{{foodtruck.truck_image}}">
                        </div>
                        <div class="form-group">
                            <label for="input_starttime">Opening Time</label>
                            <input placeholder="Selected time" type="time" id="input_starttime"
                                class="form-control timepicker time" name="open_time"
                                value="{{foodtruck.opening_time}}">
                        </div>
                        <div class="form-group">
                            <label for="input_starttime">Closing Time</label>
                            <input placeholder="Selected time" type="time" id="input_starttime"
                                class="form-control timepicker time" name="close_time"
                                value="{{foodtruck.closing_time}}">
                        </div>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

    });
</script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="slider">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
          
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img src="{% static 'images/slider1.jpg' %}" alt="Los Angeles">
              </div>
          
              <div class="item">
                <img src="{% static 'images/slider2.jpg' %}" alt="Chicago">
              </div>
          
              <div class="item">
                <img src="{% static 'images/slider3.jpg' %}" alt="New York">
              </div>
            </div>
          
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
    </div>

    <div class="container">
      <h1 class="heading">Latest Added Trucks</h1>
      {% if trucks %}
      {% for x in trucks %}
      <div class="col-md-4 truck-card">
        <div class="card">
          <img src="/media/{{x.truck_image}}" class="card-img-top" alt="{{x.truck_image}}">
          <div class="card-body">
            <h5 class="card-title">Food Type: {{x.foodtype}}
            </h5>
            <p class="card-text location">Location: {{x.location}}</p>
            <div class="card-info">
              <p class="card-text"><i class="fas fa-user"></i> Truck Owner: {{x.owner_name}}</p>
              <p class="card-text"><i class="fas fa-lock-open"></i> Opening Time: <span
                  id="opentime">{{x.opening_time}}</span></p>
              <p class="card-text"><i class="fas fa-lock"></i> Closing Time: <span
                  id="closetime">{{x.closing_time}}</span></p>
              <p class="card-text"><i class="fas fa-store"></i> Truck Status:
                <span id="truck-status">
                  {% if current_time > x.opening_time and current_time < x.closing_time %}
                    OPEN
                  {% else %}
                   CLOSED
                  {% endif %}
                </span>
              </p>
  
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

      {% endif %}
    </div>

    {% endblock %}